<?php
// Generated by Gemini

// Variables d'entorn estàndards d'AWS RDS
$host = getenv('RDS_HOSTNAME') ?: 'localhost';
$db   = getenv('RDS_DB_NAME')   ?: 'contactes';
$user = getenv('RDS_USERNAME') ?: '';
$pass = getenv('RDS_PASSWORD') ?: '';
$port = getenv('RDS_PORT')     ?: '3306';

$dsn = "mysql:host=$host;dbname=$db;port=$port;charset=utf8mb4";

try {
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
} catch (PDOException $e) {
    die("Error de connexió: " . $e->getMessage());
}
?>
