<?php
// Generated by Gemini

require_once 'db.php';

// Processar el formulari si s'ha enviat
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !empty($_POST['nom'])) {
    $stmt = $pdo->prepare("INSERT INTO contactes (nom, email) VALUES (?, ?)");
    $stmt->execute([$_POST['nom'], $_POST['email']]);
    header("Location: index.php");
    exit();
}

// Obtenir tots els contactes
$contactes = $pdo->query("SELECT * FROM contactes ORDER BY id DESC")->fetchAll();
?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Agenda PHP a AWS</title>
    <style>
        body { font-family: sans-serif; background: #f4f4f4; padding: 20px; }
        .container { max-width: 500px; background: white; padding: 20px; margin: auto; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        input { width: 100%; padding: 10px; margin: 10px 0; box-sizing: border-box; }
        button { background: #ff9900; border: none; padding: 10px; width: 100%; cursor: pointer; font-weight: bold; }
        ul { list-style: none; padding: 0; }
        li { background: #eee; margin: 5px 0; padding: 10px; border-radius: 4px; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Agenda de Contactes</h1>
        <form method="POST">
            <input type="text" name="nom" placeholder="Nom complet" required>
            <input type="email" name="email" placeholder="Correu electrònic">
            <button type="submit">Afegir Contacte</button>
        </form>

        <hr>

        <h2>Contactes Registrats</h2>
        <ul>
            <?php foreach ($contactes as $c): ?>
                <li>
                    <strong><?= htmlspecialchars($c['nom']) ?></strong><br>
                    <small><?= htmlspecialchars($c['email']) ?></small>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</body>
</html>
